<a href="https://colab.research.google.com/github/karthiga3011/masai/blob/main/Firstname_Lastname_Assignment.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

data = np.array([[22.5, 19.0, 31.2, 28.7, 25.1],
                 [17.3, 22.8, 30.5, 26.4, 21.9],
                 [33.1, 29.6, 18.4, 24.0, 27.8],
                 [20.2, 23.5, 31.9, 28.1, 22.6]])


print("Shape of data:", data.shape)

Shape of data: (4, 5)


In [2]:
mean_per_station = data.mean(axis=1)
print("Mean temperature per station:", mean_per_station)

Mean temperature per station: [25.3  23.78 26.58 25.26]


In [3]:
mask = data > 28.0
above_28 = data[mask]
print("Temperatures above 28°C:", above_28)

Temperatures above 28°C: [31.2 28.7 30.5 33.1 29.6 31.9 28.1]


In [4]:
normalized = (data - data.min()) / (data.max() - data.min())
print("Normalized data:\n", np.round(normalized, 2))

Normalized data:
 [[0.33 0.11 0.88 0.72 0.49]
 [0.   0.35 0.84 0.58 0.29]
 [1.   0.78 0.07 0.42 0.66]
 [0.18 0.39 0.92 0.68 0.34]]
